/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StudentController;
import static Controller.StudentController.Form;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Dilmini Tharuka
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        addresTF = new javax.swing.JTextField();
        ageCMB = new javax.swing.JComboBox<>();
        maleRBtnsTF = new javax.swing.JRadioButton();
        femaleRBtn = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/library-management-system-LMS-educational-ERP-software.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 204, 0));
        setLocation(new java.awt.Point(325, 125));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("   Student Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 137, 24));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        nameTF.setBackground(new java.awt.Color(255, 255, 204));
        nameTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 244, -1));

        addresTF.setBackground(new java.awt.Color(255, 255, 204));
        addresTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addresTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresTFActionPerformed(evt);
            }
        });
        jPanel1.add(addresTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 244, -1));

        ageCMB.setBackground(new java.awt.Color(255, 255, 204));
        ageCMB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ageCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10-15", "16-19" }));
        ageCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageCMBActionPerformed(evt);
            }
        });
        jPanel1.add(ageCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        maleRBtnsTF.setBackground(new java.awt.Color(255, 255, 204));
        maleRBtnsTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        maleRBtnsTF.setText("Male");
        jPanel1.add(maleRBtnsTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        femaleRBtn.setBackground(new java.awt.Color(255, 255, 204));
        femaleRBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        femaleRBtn.setText("Female");
        jPanel1.add(femaleRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        submitBtn.setBackground(new java.awt.Color(255, 255, 204));
        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        resetBtn.setBackground(new java.awt.Color(255, 255, 204));
        resetBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        exitBtn.setBackground(new java.awt.Color(255, 255, 204));
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("View Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/library-management-system-LMS-educational-ERP-software.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 554, 349));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/library-management-system-LMS-educational-ERP-software.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 630, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageCMBActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
            String gender = null;
                if (maleRBtnsTF.isSelected()) {
                    gender = "Male";
                    } else if (femaleRBtn.isSelected()) {
                        gender = "Female";
    }//GEN-LAST:event_submitBtnActionPerformed
        String age = ageCMB.getSelectedItem().toString();
        StudentController.Form(nameTF.getText(), addresTF.getText(),gender, age);
            clearField();
 } 
    private void clearField() {
        nameTF.setText("");
        addresTF.setText("");
        maleRBtnsTF.setSelected(true);
    }
    private void addresTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresTFActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        maleRBtnsTF.setSelected(false);
        femaleRBtn.setSelected(false);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new ViewRecords().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresTF;
    private javax.swing.JComboBox<String> ageCMB;
    private javax.swing.JButton exitBtn;
    private javax.swing.JRadioButton femaleRBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton maleRBtnsTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables

    
  
    }

    
    

